// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcessMap.Api.Infrastructure;

#nullable disable

namespace ProcessMap.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304160612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProcessMap.Api.Domain.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("ProcessMap.Api.Domain.Entities.ProcessNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<int>("Importance")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("ParentId");

                    b.ToTable("ProcessNodes");
                });

            modelBuilder.Entity("ProcessMap.Api.Domain.Entities.ProcessSystemTool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProcessNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcessNodeId");

                    b.ToTable("ProcessSystemTools");
                });

            modelBuilder.Entity("ProcessMap.Api.Domain.Entities.ProcessNode", b =>
                {
                    b.HasOne("ProcessMap.Api.Domain.Entities.Area", "Area")
                        .WithMany("Processos")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProcessMap.Api.Domain.Entities.ProcessNode", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Area");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("ProcessMap.Api.Domain.Entities.ProcessSystemTool", b =>
                {
                    b.HasOne("ProcessMap.Api.Domain.Entities.ProcessNode", "Process")
                        .WithMany("Sistemas")
                        .HasForeignKey("ProcessNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Process");
                });

            modelBuilder.Entity("ProcessMap.Api.Domain.Entities.Area", b =>
                {
                    b.Navigation("Processos");
                });

            modelBuilder.Entity("ProcessMap.Api.Domain.Entities.ProcessNode", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Sistemas");
                });
#pragma warning restore 612, 618
        }
    }
}
